#ifndef COMMON_H
#define COMMON_H

#include <cstdint>

typedef enum
{
    CONVOLUTION_FWD_ALGO_IMPLICIT_GEMM = 0,
    CONVOLUTION_FWD_ALGO_IMPLICIT_PRECOMP_GEMM = 1,
    CONVOLUTION_FWD_ALGO_GEMM = 2,
    CONVOLUTION_FWD_ALGO_DIRECT = 3,
    CONVOLUTION_FWD_ALGO_FFT = 4,
    CONVOLUTION_FWD_ALGO_FFT_TILING = 5,
    CONVOLUTION_FWD_ALGO_WINOGRAD = 6,
    CONVOLUTION_FWD_ALGO_WINOGRAD_NONFUSED = 7,
    CONVOLUTION_FWD_ALGO_COUNT = 8
} ConvolutionFwdAlgo_t;

#endif